#!/usr/bin/env python3
"""bundle: inline the shared MicroPython modules + a camera's app into ONE
app.py, because the OTA channel installs exactly one file.

    bundle.py <camera dir> [-o out.py]

Reads `[bundle] order = [...]` from the camera's camera.toml. Entries are
"common:<module>" (runtime/micropython/<module>.py) or a file name
relative to <camera>/software/app/. Intra-bundle imports of the form
`from <module> import *` / `import <module>` are dropped; everything else
(board modules, secrets) stays. The result is compile-checked.
"""
import argparse
import re
import sys
import tomllib
from pathlib import Path

COMMON = Path(__file__).resolve().parent


def bundle(camera_dir: Path) -> str:
    manifest = tomllib.loads((camera_dir / 'camera.toml').read_text())
    order = manifest.get('bundle', {}).get('order')
    if not order:
        sys.exit(f'{camera_dir}/camera.toml: no [bundle] order')
    files = []
    for entry in order:
        if entry.startswith('common:'):
            files.append(COMMON / (entry[7:] + '.py'))
        else:
            files.append(camera_dir / 'software' / 'app' / entry)
    names = {f.stem for f in files}
    strip = re.compile(r'^(?:from (%s) import \*|import (%s))\s*$' % ('|'.join(names), '|'.join(names)))
    out = ['# GENERATED by runtime/micropython/bundle.py from %s — do not edit; edit the sources.'
           % camera_dir.name, '# order: %s' % ', '.join(order), '']
    for f in files:
        src = f.read_text()
        out.append('# ' + '=' * 70)
        out.append('# %s' % f.relative_to(camera_dir.parent.parent) if f.is_relative_to(camera_dir.parent.parent) else '# %s' % f)
        out.append('# ' + '=' * 70)
        for line in src.splitlines():
            if strip.match(line):
                continue
            out.append(line)
        out.append('')
    text = '\n'.join(out) + '\n'
    compile(text, 'app.py', 'exec')
    return text


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('camera', type=Path)
    ap.add_argument('-o', '--out', type=Path)
    a = ap.parse_args()
    text = bundle(a.camera.resolve())
    out = a.out or (a.camera / 'software' / 'build' / 'app.py')
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print(f'{out} ({len(text)} bytes)')


if __name__ == '__main__':
    main()
