#!/usr/bin/env python3
"""Write secrets.py for this camera from ~/.dusty/{config,secrets}.toml.

  ./gen_secrets.py            # LAN path: [server].host :gate_port (blob gate, 8089), plain HTTP + token
  ./gen_secrets.py --public   # Funnel path: [server].public_host :public_port, TLS + token

Both go through the blob gate (frames -> ingest, telemetry -> MQTT), so what
runs at home is exactly what runs remotely except for TLS.

Deploy the result to /flash/secrets.py (USB drive copy; not OTA-managed).
"""
import pathlib, sys, tomllib
HERE = pathlib.Path(__file__).resolve().parent
C = tomllib.loads((pathlib.Path.home() / '.dusty/config.toml').read_text())
S = tomllib.loads((pathlib.Path.home() / '.dusty/secrets.toml').read_text())
cam = C['camera']['openmv_rt1062']; tok = S['camera']['openmv_rt1062']['ota_token']
public = '--public' in sys.argv
vals = {
    'DEVICE': cam['device'], 'MQTT_PASS': S['mqtt']['password'], 'MQTT_TOPIC': cam['device'],
    'MQTT_USER': S['mqtt']['user'], 'OTA_PORT': cam['ota_port'], 'OTA_TOKEN': tok,
    'SERVER_HOST': C['server']['public_host'] if public else C['server']['host'],
    'SERVER_PORT': C['server']['public_port'] if public else C['server'].get('gate_port', 8089),
    'SERVER_TLS': public, 'BLOB_TOKEN': S['sensorhub']['blob_token'],
    'WIFI_PASS': S['wifi']['password'], 'WIFI_SSID': S['wifi']['ssid'],
}
out = ['# GENERATED by gen_secrets.py from ~/.dusty/ — do not edit.',
       '# camera: openmv_rt1062  path: %s' % ('public (Funnel, TLS)' if public else 'LAN'),
       '# Tuning (period, diff thresholds, heartbeat, telemetry) is NOT here: it is',
       '# stamped into sensorhub_cam.py (OTA-updatable) by the same script.', '']
out += ['%s = %r' % (k, v) for k, v in vals.items()]
(HERE / 'secrets.py').write_text('\n'.join(out) + '\n')
print('secrets.py ->', vals['SERVER_HOST'], vals['SERVER_PORT'], 'tls' if public else 'plain')

# tuning block in the app (OTA path)
tuning = {k: cam[k] for k in ('period_s', 'diff_min_frac', 'diff_l_thresh', 'heartbeat_s', 'telemetry_s')}
tuning['capture_framesize'] = cam.get('capture_framesize', 'WQXGA2')   # sensor.<NAME>; '' = VGA only
tuning['capture_settle_ms'] = cam.get('capture_settle_ms', 400)
tuning['focus_secs'] = cam.get('focus_secs', 300)
app = HERE / 'sensorhub_cam.py'
src = app.read_text()
import re
new = re.sub(r'^TUNING = \{.*\}$', 'TUNING = %r' % tuning, src, count=1, flags=re.M)
if new == src and 'TUNING = %r' % tuning not in src:
    sys.exit('sensorhub_cam.py: TUNING line not found')
app.write_text(new)
print('sensorhub_cam.py tuning ->', tuning)
